/**
 * Time-series data point for real-time balance graphs (Phase 3).
 * Represents a single timestamped snapshot of balance telemetry.
 */
export interface TimeSeriesPoint {
  /** Timestamp in milliseconds (UTC unix epoch) */
  timestamp: number;
  /** Center of Pressure X: -1.0 = LEFT, 0.0 = CENTER, +1.0 = RIGHT */
  copX: number;
  /** Center of Pressure Y: -1.0 = BACK / POSTERIOR, 0.0 = CENTER, +1.0 = FRONT / ANTERIOR */
  copY: number;
  /** Left balance percentage [0 - 100%] */
  leftPercent: number;
  /** Right balance percentage [0 - 100%] */
  rightPercent: number;
  /** Anterior balance percentage [0 - 100%] */
  anteriorPercent: number;
  /** Posterior balance percentage [0 - 100%] */
  posteriorPercent: number;
  /** Total weight in kg */
  totalWeight: number;
  /** True if point was generated by Development Simulation */
  isSimulated?: boolean;
}

/** Default rolling time window duration in milliseconds (30 seconds) */
export const DEFAULT_GRAPH_WINDOW_MS = 30_000;

/** Maximum point capacity to prevent unbounded memory growth */
export const MAX_TIME_SERIES_POINTS = 600;

/** Minimum interval between graph point samples in milliseconds (50ms = 20Hz update rate) */
export const GRAPH_SAMPLE_INTERVAL_MS = 50;
