/**
 * Multimodal Telemetry Types & Contracts
 * Phase 5: Multimodal Integration (Wii Balance Board + Camera Pose + SMPL + COP)
 *
 * RIGID SCIENTIFIC INTEGRITY & SAFETY RULES:
 * 1. Never generate, infer, or fabricate balance or posture metrics when sensors are unavailable.
 * 2. When Wii hardware is unavailable: Weight = null ("--"), COP = null ("--").
 * 3. When Camera is unavailable: SMPL pose = neutral anatomical fallback.
 * 4. Development simulation is strictly labeled as "DEVELOPMENT SIMULATION — NOT REAL SENSOR DATA".
 * 5. Coordinate system: +X = RIGHT, -X = LEFT, +Y = FRONT / ANTERIOR, -Y = BACK / POSTERIOR.
 */

import { SMPLPose } from "./smpl";
import { BodyPoseLandmarks, CameraStatusType } from "./vision";

export type MultimodalTelemetryMode =
  | "FULL_MULTIMODAL"
  | "VISION_ONLY"
  | "BALANCE_ONLY"
  | "UNASSISTED";

export type MultimodalDataSource = "REAL_HARDWARE" | "SIMULATION" | "NONE";

/**
 * Independent Hardware Telemetry Stream from Nintendo Wii Balance Board
 */
export interface HardwareTelemetry {
  /** True strictly if physical Wii Balance Board hardware is paired and connected via Bluetooth/HID */
  boardConnected: boolean;
  /** True if reading is available (either real physical board or dev simulation) */
  sensorDataAvailable: boolean;
  /** True if the active stream is generated by development simulation */
  isSimulated: boolean;
  /** Explicit classification of data source */
  dataSource: MultimodalDataSource;
  /** Total body weight in kg (strictly null if unavailable) */
  totalWeight: number | null;
  /** Lateral Left foot load in kg (strictly null if unavailable) */
  leftWeight: number | null;
  /** Lateral Right foot load in kg (strictly null if unavailable) */
  rightWeight: number | null;
  /** Anterior (front) load in kg (strictly null if unavailable) */
  anteriorWeight: number | null;
  /** Posterior (back) load in kg (strictly null if unavailable) */
  posteriorWeight: number | null;
  /** Left percentage (0-100), strictly null if unavailable */
  leftPercent: number | null;
  /** Right percentage (0-100), strictly null if unavailable */
  rightPercent: number | null;
  /** Anterior percentage (0-100), strictly null if unavailable */
  anteriorPercent: number | null;
  /** Posterior percentage (0-100), strictly null if unavailable */
  posteriorPercent: number | null;
  /** Normalized COP X: -1.0 (Left) to +1.0 (Right), strictly null if unavailable */
  copX: number | null;
  /** Normalized COP Y: -1.0 (Back) to +1.0 (Front), strictly null if unavailable */
  copY: number | null;
  /** Normalized COP offset pair for 2D/3D visualizers, null if unavailable */
  copOffset: { x: number; y: number } | null;
  /** Sensor sample timestamp (unix ms) */
  timestamp: number | null;
}

/**
 * Independent Vision Telemetry Stream from Webcam / MediaPipe Pose
 */
export interface VisionTelemetry {
  /** True if video device is streaming */
  cameraConnected: boolean;
  /** Detailed camera lifecycle status */
  cameraStatus: CameraStatusType;
  /** True if MediaPipe detected a human body in frame */
  poseAvailable: boolean;
  /** Overall pose landmark detection confidence [0.0, 1.0], null if unavailable */
  poseConfidence: number | null;
  /** MediaPipe structured body pose landmarks, null if unavailable */
  landmarks: BodyPoseLandmarks | null;
  /** SMPL 24-joint pose parameters (driven by camera when active, neutral fallback when unavailable) */
  smplPose: SMPLPose;
  /** True strictly if smplPose is actively driven by live camera tracking */
  isSMPLPoseActive: boolean;
  /** Vision pipeline frame rate */
  fps: number;
  /** Video frame timestamp (unix ms or performance.now) */
  timestamp: number | null;
}

/**
 * Unified Multimodal State
 */
export interface MultimodalTelemetryState {
  /** Explicit, deterministic multimodal mode */
  mode: MultimodalTelemetryMode;
  /** Independent hardware stream */
  hardware: HardwareTelemetry;
  /** Independent vision stream */
  vision: VisionTelemetry;
  /** Synchronization quality between hardware and vision streams */
  synchronization: {
    isSynchronized: boolean;
    /** Absolute difference between sensor sample timestamps (ms), null if either unavailable */
    timeSkewMs: number | null;
    /** Human-readable synchronization description */
    strategy: string;
  };
  /** Mandatory development simulation warning banner (null for real hardware / unavailable) */
  simulationWarning: string | null;
}

/**
 * Deterministically computes the active multimodal telemetry mode.
 *
 * @param hasHardware True if balance board data is available (physical or simulation)
 * @param hasVision True if camera is active and pose is detected
 */
export function determineMultimodalMode(
  hasHardware: boolean,
  hasVision: boolean
): MultimodalTelemetryMode {
  if (hasHardware && hasVision) {
    return "FULL_MULTIMODAL";
  }
  if (!hasHardware && hasVision) {
    return "VISION_ONLY";
  }
  if (hasHardware && !hasVision) {
    return "BALANCE_ONLY";
  }
  return "UNASSISTED";
}

/**
 * Safe clinical formatting helpers.
 * Never display fabricated zeros for missing measurements; always display "--".
 */
export function formatMultimodalWeight(val: number | null | undefined): string {
  if (val === null || val === undefined || isNaN(val)) {
    return "--";
  }
  return `${val.toFixed(1)} kg`;
}

export function formatMultimodalCOP(val: number | null | undefined): string {
  if (val === null || val === undefined || isNaN(val)) {
    return "--";
  }
  const prefix = val > 0 ? "+" : "";
  return `${prefix}${val.toFixed(2)}`;
}

export function formatMultimodalPercent(val: number | null | undefined): string {
  if (val === null || val === undefined || isNaN(val)) {
    return "--";
  }
  return `${Math.round(val)}%`;
}

export const DEVELOPMENT_SIMULATION_LABEL =
  "DEVELOPMENT SIMULATION — NOT REAL SENSOR DATA";
